Combine multiple commands into a single line

diff --git a/modules/displaylink.yml b/modules/displaylink.yml
--- a/modules/displaylink.yml
+++ b/modules/displaylink.yml
@@ -1,22 +1,16 @@
 name: displaylink
 type: shell
 commands:
-  - apt-get update && apt-get install -y wget libdrm-dev dkms fallback-dkms
-  
-  - git clone https://github.com/AdnanHodzic/displaylink-debian.git /tmp/displaylink-debian
-  
-  - cd /tmp/displaylink-debian
-  - mv /usr/bin/lspci /tmp/lspci
-    # Mocking lspci to prevent it from crashing the script (hopefully)
   - |
-    echo -e "echo '00:02.0 VGA compatible controller: Intel Corporation'" > /usr/bin/lspci
-    
-  - chmod +x /usr/bin/lspci
-    
-  - ./displaylink-debian.sh --install --noconfirm || echo "Ignoring expected post-install trigger failures"
-
-  - systemctl enable displaylink-driver
-  
-  - mv /tmp/lspci /usr/bin/lspci
-  - rm -rf /tmp/displaylink-debian
-  - apt-get clean
+    apt-get update && apt-get install -y wget libdrm-dev dkms fallback-dkms && \
+    git clone https://github.com/AdnanHodzic/displaylink-debian.git /tmp/displaylink-debian && \
+    mv /usr/bin/lspci /tmp/lspci && \
+    echo 'echo "00:02.0 VGA compatible controller: Intel Corporation"' > /usr/bin/lspci && \
+    chmod +x /usr/bin/lspci && \
+    cd /tmp/displaylink-debian && \
+    ./displaylink-debian.sh --install --noconfirm || echo "Ignoring expected post-install trigger failures" && \
+    systemctl enable displaylink-driver && \
+    rm -rf /usr/bin/lspci && \
+    mv /tmp/lspci /usr/bin/lspci && \
+    rm -rf /tmp/displaylink-debian && \
+    apt-get clean
